fix: user 정보 조회 API 추가
undefined-dev-ko/ship-check-be pull request #13
Opened 2024-06-01 10:13 UTC by songseungeun

- fix: user 정보 조회 API 추가
- 저번 모임때 작업했던 회원정보 조회 API 입니다.

2024-06-01 13:30 UTC, Jang184 requested changes

2024-06-01 13:30 UTC, Jang184 commented on src/user/user.service.ts
> +  async getUser({ userId }): Promise<User> {
parameter에 타입 지정해주면 좋을 것 같습니다!

2024-06-01 13:30 UTC, Jang184 commented on src/user/user.controller.ts
> +  @Get("/user")
이대로하면 api 주소가 GET /user/user가 됩니다
저번 모임때 GET /user/detail 로 하기로 했던 것 같은데 괜찮을까욥??

2024-06-02 03:19 UTC, songseungeun commented on src/user/user.controller.ts
> +  @Get("/user")
아아 그러네요..! 수정하겠습니다!

2024-06-02 04:26 UTC, Jang184 approved these changes

2024-06-05 09:34 UTC, KadyoYang approved these changes
리뷰 올린것 확인후 추가하시고 suqash merge 하시면 될것같습니다..! lgtm!

2024-06-05 09:34 UTC, KadyoYang commented on src/user/user.service.ts
> +    const result = await this.dataSource.manager.findOne(User, {
typeorm의 manager.findOne의 결과로 undefined가 잠재적으로 리턴될수있습니다! 만약에 매칭되는 결과가 없을시에는요..! 그때는 

if(!result){
throw new NotFoundException();
}

을 해주시는것 나쁘지않습니다..!

2024-06-06 10:47 UTC, merged